# Generated by Django 6.1 on 2026-09-22 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_caja", "0001_initial"),
        ("app_clientes", "0001_initial"),
        ("app_empleados", "0001_initial"),
        ("app_inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolucionDIAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("POS", "Documento Equivalente POS"),
                            ("FE", "Factura Electrónica de Venta"),
                        ],
                        default="POS",
                        max_length=5,
                    ),
                ),
                ("numero_resolucion", models.CharField(max_length=50)),
                ("prefijo", models.CharField(blank=True, default="", max_length=10)),
                ("rango_desde", models.PositiveIntegerField()),
                ("rango_hasta", models.PositiveIntegerField()),
                ("ultimo_numero", models.PositiveIntegerField(default=0)),
                ("longitud_ceros", models.PositiveSmallIntegerField(default=8)),
                ("fecha_inicio_vigencia", models.DateField()),
                ("fecha_fin_vigencia", models.DateField()),
                (
                    "clave_tecnica",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Descuento", max_length=100)),
                (
                    "codigo_cupon",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "tipo_calculo",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje (%)"),
                            ("MONTO_FIJO", "Monto Fijo ($)"),
                        ],
                        default="PORCENTAJE",
                        max_length=15,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            ("GENERAL", "A toda la factura"),
                            ("PRODUCTO", "A un producto específico"),
                            ("CATEGORIA", "A una categoría específica"),
                        ],
                        default="GENERAL",
                        max_length=15,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("limite_usos", models.PositiveIntegerField(blank=True, null=True)),
                ("veces_usado", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categorías completas a las que aplica este descuento",
                        related_name="descuentos",
                        to="app_inventario.categoria",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Productos específicos a los que aplica este descuento",
                        related_name="descuentos",
                        to="app_inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento",
                "verbose_name_plural": "Descuentos",
            },
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                (
                    "total_devuelto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
                (
                    "sesion_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_caja.sesioncaja",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleDevolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("retorno_inventario", models.BooleanField(default=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventario.producto",
                    ),
                ),
                (
                    "devolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app_ventas.devolucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "monto_descuento",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_impuesto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_PAGO", "Pendiente por pagar"),
                            ("PAGADA", "Pagada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="PENDIENTE_PAGO",
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_clientes.cliente",
                    ),
                ),
                (
                    "descuento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="app_ventas.descuento",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
                (
                    "sesion_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_caja.sesioncaja",
                    ),
                ),
                (
                    "resolucion_dian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="app_ventas.resoluciondian",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="devolucion",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devoluciones",
                to="app_ventas.factura",
            ),
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "costo_unitario_historico",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tarifa_impuesto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_impuesto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventario.producto",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app_ventas.factura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA_DEBITO", "Tarjeta de Debito"),
                            ("TARJETA_CREDITO", "Tarjeta de Credito"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "referencia_transferencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="app_ventas.factura",
                    ),
                ),
            ],
        ),
    ]
