# Generated by Django 6.0.6 on 2026-09-22 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_caja', '0002_alter_sesioncaja_empleado_and_more'),
        ('app_clientes', '0002_cliente_chk_cliente_identificacion_no_vacia_and_more'),
        ('app_empleados', '0002_empleado_chk_empleado_salario_gte_0_and_more'),
        ('app_inventario', '0002_categoria_chk_categoria_nombre_no_vacio_and_more'),
        ('app_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='monto_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='tarifa_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='chk_descuento_valor_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_calculo', 'PORCENTAJE'), ('valor__lte', 100)), ('tipo_calculo', 'MONTO_FIJO'), _connector='OR'), name='chk_descuento_porcentaje_max_100'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('veces_usado__gte', 0)), name='chk_descuento_veces_usado_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('limite_usos__isnull', True), ('limite_usos__gt', 0), _connector='OR'), name='chk_descuento_limite_usos_valido'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('limite_usos__isnull', True), ('veces_usado__lte', models.F('limite_usos')), _connector='OR'), name='chk_descuento_usos_no_superan_limite'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_descuento_vigencia_fechas'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='chk_descuento_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_det_dev_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='chk_det_dev_precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_det_fac_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='chk_det_fac_precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario_historico__gte', 0)), name='chk_det_fac_costo_historico_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa_impuesto__gte', 0)), name='chk_det_fac_tarifa_impuesto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('monto_impuesto__gte', 0)), name='chk_det_fac_monto_impuesto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='chk_det_fac_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.UniqueConstraint(fields=('factura', 'producto'), name='uq_det_fac_producto'),
        ),
        migrations.AddConstraint(
            model_name='devolucion',
            constraint=models.CheckConstraint(condition=models.Q(('total_devuelto__gt', 0)), name='chk_dev_total_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='devolucion',
            constraint=models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='chk_dev_motivo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('monto_descuento__gte', 0)), name='chk_factura_monto_descuento_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='chk_factura_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('total_impuesto__gte', 0)), name='chk_factura_total_impuesto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_factura_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('codigo', ''), _negated=True), name='chk_factura_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='pagofactura',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_pago_monto_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('rango_desde__gt', 0)), name='chk_dian_rango_desde_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('rango_hasta__gte', models.F('rango_desde'))), name='chk_dian_rango_hasta_gte_desde'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('ultimo_numero', 0), models.Q(('ultimo_numero__gte', models.F('rango_desde')), ('ultimo_numero__lte', models.F('rango_hasta'))), _connector='OR'), name='chk_dian_ultimo_numero_en_rango'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('longitud_ceros__gt', 0)), name='chk_dian_longitud_ceros_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin_vigencia__gte', models.F('fecha_inicio_vigencia'))), name='chk_dian_fechas_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='resoluciondian',
            constraint=models.CheckConstraint(condition=models.Q(('numero_resolucion', ''), _negated=True), name='chk_dian_numero_resolucion_no_vacio'),
        ),
    ]
