# Generated by Django 6.1 on 2026-09-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_empleados", "0001_initial"),
        ("app_inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("13", "Cédula de Ciudadanía (CC)"),
                            ("31", "NIT (Número de Identificación Tributaria)"),
                            ("22", "Cédula de Extranjería (CE)"),
                            ("41", "Pasaporte"),
                            ("12", "Tarjeta de Identidad"),
                            ("11", "Registro Civil"),
                            ("50", "Documento de Identificación Extranjero"),
                        ],
                        default="31",
                        max_length=2,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("razon_social", models.CharField(max_length=150)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("SOLICITADO", "Solicitado"),
                            ("EN_PROCESO", "En Proceso"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "total_estimado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True, null=True)),
                ("fecha_esperada_entrega", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to="app_proveedores.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_solicitada", models.IntegerField()),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventario.producto",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app_proveedores.ordencompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecepcionCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura_proveedor", models.CharField(max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[("RECIBIDO", "Recibida"), ("ANULADO", "Anulado")],
                        default="RECIBIDO",
                        max_length=20,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepciones",
                        to="app_proveedores.ordencompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleRecepcionCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_recibida", models.IntegerField()),
                ("cantidad_rechazada", models.IntegerField(default=0)),
                (
                    "costo_final_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                (
                    "detalle_orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_proveedores.detalleordencompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_inventario.producto",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app_proveedores.recepcioncompra",
                    ),
                ),
            ],
        ),
    ]
