# Generated by Django 6.1 on 2026-09-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("13", "Cédula de Ciudadanía (CC)"),
                            ("31", "NIT (Número de Identificación Tributaria)"),
                            ("22", "Cédula de Extranjería (CE)"),
                            ("41", "Pasaporte"),
                            ("12", "Tarjeta de Identidad"),
                            ("11", "Registro Civil"),
                            ("50", "Documento de Identificación Extranjero"),
                        ],
                        default="13",
                        max_length=2,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "salario",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("es_admin", models.BooleanField(default=False)),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
