# Generated by Django 6.1 on 2026-09-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_inicial", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monto_final_calculado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "monto_final_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierta"), ("CERRADO", "Cerrada")],
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                ("fecha_hora_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_hora_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AjustesCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("motivo", models.TextField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "sesion_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes",
                        to="app_caja.sesioncaja",
                    ),
                ),
            ],
        ),
    ]
