# Generated by Django 6.0.6 on 2026-09-22 21:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_caja", "0001_initial"),
        ("app_empleados", "0002_empleado_chk_empleado_salario_gte_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesioncaja",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sesiones_caja",
                to="app_empleados.empleado",
            ),
        ),
        migrations.AlterField(
            model_name="sesioncaja",
            name="fecha_hora_apertura",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="ajustescaja",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gt", 0)), name="chk_ajuste_monto_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="ajustescaja",
            constraint=models.CheckConstraint(
                condition=models.Q(("tipo__in", ["INGRESO", "EGRESO"])),
                name="chk_ajuste_tipo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="ajustescaja",
            constraint=models.CheckConstraint(
                condition=models.Q(("motivo", ""), _negated=True),
                name="chk_ajuste_motivo_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto_inicial__gte", 0)),
                name="chk_caja_monto_inicial_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto_final_calculado__gte", 0)),
                name="chk_caja_monto_final_calc_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("monto_final_real__isnull", True),
                    ("monto_final_real__gte", 0),
                    _connector="OR",
                ),
                name="chk_caja_monto_final_real_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estado", "CERRADO"),
                        ("fecha_hora_cierre__isnull", False),
                        ("monto_final_real__isnull", False),
                    ),
                    ("estado", "ABIERTO"),
                    _connector="OR",
                ),
                name="chk_caja_consistencia_cierre",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_hora_cierre__isnull", True),
                    ("fecha_hora_cierre__gte", models.F("fecha_hora_apertura")),
                    _connector="OR",
                ),
                name="chk_caja_cierre_gte_apertura",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ABIERTO")),
                fields=("empleado",),
                name="uq_sesion_activa_por_empleado",
            ),
        ),
    ]
