# Generated by Django 6.1 on 2026-09-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo_tributario", models.CharField(max_length=10, unique=True)),
                (
                    "tarifa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[
                            ("PORCENTAJE", "Porcentaje (%)"),
                            ("FIJO", "Monto Fijo por Unidad"),
                        ],
                        default="PORCENTAJE",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "costo_compra",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_actual", models.IntegerField(default=0)),
                ("stock_minimo", models.IntegerField(default=5)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="app_inventario.categoria",
                    ),
                ),
                (
                    "impuesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="app_inventario.impuesto",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="app_inventario.marca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra"),
                            ("VENTA", "Venta"),
                            ("DEVOLUCION", "Devolución"),
                            ("AJUSTE", "Ajuste"),
                            ("MERMA", "Merma"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referencia_origen",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cantidad", models.IntegerField()),
                ("stock_anterior", models.IntegerField()),
                ("stock_posterior", models.IntegerField()),
                ("motivo", models.TextField(blank=True, default="")),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_empleados.empleado",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="app_inventario.producto",
                    ),
                ),
            ],
        ),
    ]
