# Generated by Django 6.0.6 on 2026-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_empleados", "0002_empleado_chk_empleado_salario_gte_0_and_more"),
        ("app_inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.CheckConstraint(
                condition=models.Q(("nombre", ""), _negated=True),
                name="chk_categoria_nombre_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="impuesto",
            constraint=models.CheckConstraint(
                condition=models.Q(("tarifa__gte", 0)), name="chk_impuesto_tarifa_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="impuesto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tarifa__lte", 100), ("tipo_impuesto", "PORCENTAJE")),
                    ("tipo_impuesto", "FIJO"),
                    _connector="OR",
                ),
                name="chk_impuesto_porcentaje_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="impuesto",
            constraint=models.CheckConstraint(
                condition=models.Q(("codigo_tributario", ""), _negated=True),
                name="chk_impuesto_codigo_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="impuesto",
            constraint=models.CheckConstraint(
                condition=models.Q(("nombre", ""), _negated=True),
                name="chk_impuesto_nombre_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="marca",
            constraint=models.CheckConstraint(
                condition=models.Q(("nombre", ""), _negated=True),
                name="chk_marca_nombre_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="chk_movimiento_cantidad_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_anterior__gte", 0)),
                name="chk_movimiento_stock_anterior_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_posterior__gte", 0)),
                name="chk_movimiento_stock_posterior_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("costo_compra__gte", 0)),
                name="chk_producto_costo_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_venta__gte", models.F("costo_compra"))),
                name="chk_producto_precio_gte_costo",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_actual__gte", 0)),
                name="chk_producto_stock_actual_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_minimo__gte", 0)),
                name="chk_producto_stock_minimo_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("nombre", ""), _negated=True),
                name="chk_producto_nombre_no_vacio",
            ),
        ),
    ]
