# Generated by Django 6.1 on 2026-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("13", "Cédula de Ciudadanía (CC)"),
                            ("31", "NIT (Número de Identificación Tributaria)"),
                            ("22", "Cédula de Extranjería (CE)"),
                            ("41", "Pasaporte"),
                            ("12", "Tarjeta de Identidad"),
                            ("11", "Registro Civil"),
                            ("50", "Documento de Identificación Extranjero"),
                        ],
                        default="13",
                        max_length=2,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
