# Generated by Django 6.1 on 2026-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="es_admin",
            field=models.BooleanField(default=False),
        ),
    ]
